-- ============ 作品集留言板建表脚本 ============
-- 使用方法：Supabase 控制台左侧栏 → SQL Editor → New query →
-- 粘贴本文件全部内容 → 点 Run，看到 Success 即可

-- 1. 留言表
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    nickname text default '' not null,
    content text not null,
    created_at timestamptz not null default now()
);

-- 开启行级安全
alter table public.messages enable row level security;

-- 所有人可读
create policy "messages_select"
    on public.messages for select
    using (true);

-- 所有人可留言（内容 1~500 字，昵称最长 30 字）
create policy "messages_insert"
    on public.messages for insert
    with check (
        char_length(content) between 1 and 500
        and char_length(coalesce(nickname, '')) <= 30
    );

-- 禁止匿名用户更新与删除（不建 update/delete 策略即默认拒绝）

-- 2. 点赞表（永远只有一行，count 为总赞数）
create table if not exists public.likes (
    id int primary key default 1,
    count bigint not null default 0,
    constraint likes_single_row check (id = 1)
);
insert into public.likes (id, count) values (1, 0) on conflict do nothing;

alter table public.likes enable row level security;

create policy "likes_select"
    on public.likes for select
    using (true);

-- 3. 点赞自增函数：访客只能"加一"，不能直接改数字
create or replace function public.increment_likes()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_count bigint;
begin
    update public.likes
    set count = count + 1
    where id = 1
    returning count into new_count;
    return new_count;
end;
$$;

-- 允许所有人调用该函数
grant execute on function public.increment_likes() to anon;
